version: '3'

services:
  backend:
    build:
      context: https://github.com/mjosejunior/mvp_jrmj_sp2_back.git
    ports:
      - "5001:5001"
    volumes:
      - "./database:/app/database"  # mapeando o diretório do SQLite para o contêiner

  frontend:
    build: 
      context: https://github.com/mjosejunior/mvp_jrmj_sp2_front.git
    ports:
      - "80:80"
    depends_on:
      - backend  # Se o frontend só deve iniciar depois do backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
