version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - "./database:/app/database"  # mapeando o diretório do SQLite para o contêiner

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  database:
    image: "linuxserver/sqlite3"
    volumes:
      - "./database:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
